const keywords = [
    "LEADERSHIP", "TEAMWORK", "COMMUNICATION", "PROBLEM-SOLVING", "CRITICAL THINKING", "ADAPTABILITY",
    "TIME MANAGEMENT", "PROJECT MANAGEMENT", "DECISION MAKING", "ANALYTICAL SKILLS", "CREATIVITY",
    "ATTENTION TO DETAIL", "MULTITASKING", "RESEARCH", "NEGOTIATION", "CONFLICT RESOLUTION",
    "CUSTOMER SERVICE", "SALES", "MARKETING", "DATA ANALYSIS", "STRATEGIC PLANNING", "BUDGET MANAGEMENT",
    "PUBLIC SPEAKING", "PRESENTATION SKILLS", "RISK MANAGEMENT", "QUALITY CONTROL", "INTERPERSONAL SKILLS",
    "LEADERSHIP DEVELOPMENT", "ORGANIZATIONAL SKILLS", "PROBLEM IDENTIFICATION", "SALES STRATEGY",
    "MARKET RESEARCH", "CLIENT RELATIONS", "TEAM LEADERSHIP", "CROSS-FUNCTIONAL COLLABORATION",
    "VENDOR MANAGEMENT", "CLIENT ACQUISITION", "MARKET ANALYSIS", "CUSTOMER RELATIONSHIP MANAGEMENT (CRM)",
    "BUSINESS DEVELOPMENT", "JAVASCRIPT", "PYTHON", "JAVA", "C++", "RUBY", "PHP", "SWIFT", "C#", "SQL", "HTML/CSS",
    "TYPESCRIPT", "GO", "KOTLIN", "RUST", "MATLAB", "PERL", "SHELL SCRIPTING", "R", "SCALA", "VB.NET",
    "OBJECTIVE-C", "ASSEMBLY", "DART", "COBOL", "LUA", "VBA", "GROOVY", "PL/SQL", "ABAP",
    "MICROSOFT OFFICE SUITE", "ADOBE CREATIVE SUITE", "SALESFORCE", "SAP", "TABLEAU", "GOOGLE ANALYTICS",
    "AUTOCAD", "MATLAB", "HADOOP", "DOCKER", "KUBERNETES", "AWS", "AZURE", "GIT/GITHUB", "JENKINS", "JIRA",
    "SLACK", "TRELLO", "WORDPRESS", "DRUPAL", "JOOMLA", "SHAREPOINT", "CRM SOFTWARE", "ERP SYSTEMS",
    "VIRTUALIZATION", "NETWORK ADMINISTRATION", "DEVOPS", "AGILE METHODOLOGY", "SCRUM", "BIG DATA",
    "HEALTHCARE", "FINANCE", "EDUCATION", "INFORMATION TECHNOLOGY (IT)", "RETAIL", "MANUFACTURING", "REAL ESTATE",
    "HOSPITALITY", "CONSTRUCTION", "NONPROFIT", "PHARMACEUTICALS", "MARKETING", "E-COMMERCE", "TELECOMMUNICATIONS",
    "AEROSPACE", "ENERGY", "ENTERTAINMENT", "AUTOMOTIVE", "GOVERNMENT", "ENVIRONMENTAL",
    "PMP (PROJECT MANAGEMENT PROFESSIONAL)", "CPA (CERTIFIED PUBLIC ACCOUNTANT)", "CFA (CHARTERED FINANCIAL ANALYST)",
    "PHR (PROFESSIONAL IN HUMAN RESOURCES)", "SHRM-CP (SHRM CERTIFIED PROFESSIONAL)",
    "CISSP (CERTIFIED INFORMATION SYSTEMS SECURITY PROFESSIONAL)",
    "CCNA (CISCO CERTIFIED NETWORK ASSOCIATE)", "COMPTIA A+",
    "AWS CERTIFIED SOLUTIONS ARCHITECT", "GOOGLE CLOUD PROFESSIONAL CLOUD ARCHITECT",
    "Business Strategy", "Financial Analysis", "Market Segmentation", "Brand Management", "Consumer Behavior",
    "Product Lifecycle Management", "Business Intelligence", "Stakeholder Management", "Operations Management",
    "Supply Chain Management", "Cost Reduction", "Revenue Growth", "Competitive Analysis", "Pricing Strategy",
    "Change Management", "Customer Retention", "Business Process Improvement", "Lean Management", "Six Sigma",
    "Business Transformation", "Corporate Finance", "Mergers and Acquisitions", "Business Modeling", "SWOT Analysis",
    "Business Ethics", "Business Continuity Planning", "Risk Assessment", "Inventory Management", "Lean Six Sigma",
    "E-commerce Strategy", "Business Communications", "Performance Metrics", "Customer Experience", "Business Forecasting",
    "Financial Planning", "Value Proposition", "Business Analytics", "Business Negotiation", "Contract Management",
    "Business Law", "Corporate Governance", "Business Scaling", "Business Planning", "Business Partnerships",
    "Business Consulting", "International Business", "Corporate Strategy", "Business Expansion", "Business Operations",
    "Artificial Intelligence", "Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Vision",
    "Data Mining", "Neural Networks", "Reinforcement Learning", "Supervised Learning", "Unsupervised Learning",
    "Predictive Analytics", "AI Ethics", "AI Model Training", "AI Algorithms", "AI Applications", "Chatbots",
    "AI in Healthcare", "AI in Finance", "AI in Marketing", "AI in Education", "AI in Manufacturing", "AI in Retail",
    "AI Development", "AI Research", "AI Frameworks", "AI Tools", "AI Platforms", "AI Trends", "AI Strategy",
    "AI Integration", "AI Deployment", "AI Governance", "AI Innovation", "SQL Programming", "SQL Queries",
    "SQL Database Design", "SQL Performance Tuning", "SQL Indexing", "SQL Joins", "SQL Functions", "SQL Stored Procedures",
    "SQL Server", "SQL Optimization", "SQL Reporting", "SQL Analytics", "SQL Injection Prevention", "SQL Scripting",
    "SQL Subqueries", "SQL Triggers", "SQL Views", "SQL Transactions", "SQL Constraints", "SQL Backup and Recovery",
    "SQL Data Types", "SQL Security", "SQL Partitioning", "SQL Migration", "SQL Data Modeling", "SQL Data Warehousing",
    "SQL ETL Processes", "SQL Data Cleansing", "SQL Error Handling", "SQL User Management", "SQL Best Practices",
    "SQL Database Administration", "SQL Query Analysis", "SQL Schema Design", "SQL Syntax", "SQL Data Integration",
    "SQL Monitoring", "SQL Debugging", "SQL Development", "SQL Data Manipulation", "SQL Normalization",
    "SQL Case Statements", "SQL Aggregate Functions", "SQL Window Functions", "SQL Recursive Queries",
    "SQL Pivot and Unpivot", "SQL Regular Expressions", "SQL Data Import/Export", "SQL JSON Processing", "SQL XML Processing",
    "SQL Geospatial Data", "SQL Full-Text Search", "SQL Clustered Indexes", "SQL Non-Clustered Indexes", "SQL Performance Benchmarking",
    "SQL Data Encryption", "SQL Data Compression", "SQL Execution Plans", "SQL Data Governance", "SQL Auditing",
    "SQL Job Scheduling", "SQL Server Management Studio", "SQL Data Synchronization", "SQL Stored Procedures Optimization",
    "SQL Transactions Management", "SQL Cursor Usage", "SQL Metadata Management", "SQL Data Partitioning",
    "SQL Query Optimization Techniques", "SQL Data Analysis", "SQL Disaster Recovery", "SQL Cloud Integration",
    "SQL Server Configuration", "SQL Performance Monitoring", "SQL Data Migration Strategies", "SQL High Availability",
    "SQL Data Replication", "SQL Data Sharding", "SQL Data Lakes", "SQL Hybrid Cloud", "SQL Microservices",
    "SQL Continuous Integration", "SQL Continuous Deployment", "SQL Code Review", "SQL Data Security Best Practices",
    "SQL Logging and Monitoring", "SQL Cloud Services", "SQL Scalability", "SQL System Architecture",
    "SQL Big Data", "SQL Containerization", "SQL DevOps", "SQL Testing", "SQL Compliance", "SQL Governance Policies",
    "SQL Data Lineage", "SQL Change Data Capture", "SQL Code Quality", "SQL Data Accuracy", "SQL Data Integrity",
    "SQL Data Lifecycle Management", "SQL Data Pipeline", "SQL Data Quality", "SQL Performance Tuning Tools",
    "SQL Error Handling Best Practices", "SQL Data Backup", "SQL Server Management", "SQL Analytics and Reporting",
    "SQL Integration Services", "SQL Data Warehouse Design", "SQL Data Validation", "SQL Process Automation",
    "SQL Dynamic SQL", "SQL Advanced Queries", "SQL Analytical Functions", "SQL Data Aggregation",
    "SQL Complex Joins", "SQL Query Performance", "SQL Server Maintenance", "SQL Data Security Measures",
    "SQL Data Privacy", "SQL Data Retention", "SQL Data Modeling Tools", "SQL Database Tuning", "SQL Application Development",
    "SQL Cloud Databases", "SQL Data Transformation", "SQL Cloud Migration", "SQL Best Coding Practices", "SQL Data Scalability",
    "SQL System Performance", "SQL Database Monitoring Tools", "SQL Query Profiling", "SQL Data Recovery Solutions",
    "SQL Indexing Strategies", "SQL Transaction Management Best Practices", "SQL Database Optimization",
    "SQL Data Visualization", "SQL Query Debugging", "SQL Server Performance", "SQL Data Analytics Tools",
    "SQL Cloud Management", "SQL Data Integration Tools", "SQL Performance Analysis", "SQL Development Tools",
    "SQL Database Security", "SQL Data Encryption Techniques", "SQL Cloud Architecture", "SQL Query Optimization Strategies",
    "SQL Database Maintenance", "SQL Data Management", "SQL Best Practices for Performance", "SQL Continuous Monitoring",
    "SQL Performance Metrics", "SQL Database Performance Tuning", "SQL Query Performance Tuning", "SQL Data Processing",
    "SQL Monitoring Tools", "SQL Database Backup", "SQL Data Security Techniques", "SQL Data Storage",
    "SQL Cloud Deployment", "SQL High Performance", "SQL Data Access", "SQL Data Transformation Tools",
    "SQL Cloud Database Management", "SQL Performance Tuning Best Practices", "SQL Data Engineering", "SQL System Monitoring",
    "SQL Code Optimization", "SQL Data Security Solutions", "SQL Database Security Best Practices",
    "SQL Performance Optimization", "SQL System Performance Monitoring", "SQL Cloud Services Integration",
    "SQL Data Pipeline Management", "SQL Performance Testing", "SQL Continuous Integration Tools",
    "SQL Cloud Infrastructure", "SQL Query Efficiency", "SQL Database Automation", "SQL Cloud Data Management",
    "SQL Data Orchestration", "SQL Data Pipeline Automation", "SQL System Security", "SQL Data Reliability",
    "SQL Performance Metrics Monitoring", "SQL Database Development", "SQL System Configuration",
    "SQL Data Governance Strategies", "SQL Cloud Security", "SQL Performance Analysis Tools", "SQL Data Flow",
    "SQL Query Optimization Tools", "SQL Cloud Database Optimization", "SQL Database Performance Monitoring",
    "SQL System Automation", "SQL Data Security Best Practices", "SQL Cloud Infrastructure Management",
    "SQL Performance Monitoring Tools", "SQL Data Security Management", "SQL Database Management Tools",
    "SQL System Optimization", "SQL Performance Benchmarking Tools", "SQL Data Security Policies",
    "SQL Cloud Data Security", "SQL Database Administration Best Practices", "SQL Data Privacy Management",
    "SQL Data Protection", "SQL Performance Testing Tools", "SQL Data Transformation Techniques",
    "SQL Database Management Best Practices", "SQL Cloud Data Services", "SQL Performance Metrics Analysis",
    "SQL Data Security Best Practices", "SQL Cloud Database Services", "SQL Data Analysis Tools",
    "SQL System Monitoring Tools", "SQL Data Management Strategies", "SQL Performance Monitoring Best Practices",
    "SQL Data Privacy Solutions", "SQL Cloud Database Management Tools", "SQL Performance Tuning Techniques",
    "SQL Data Transformation Best Practices", "SQL Database Development Tools", "SQL Data Management Tools",
    "SQL Data Security Policies and Procedures", "SQL Cloud Data Management Strategies", "SQL Performance Metrics Tools",
    "SQL Data Processing Techniques", "SQL Database Monitoring and Management", "SQL Data Security and Privacy",
    "SQL Cloud Database Performance", "SQL System Performance Optimization", "SQL Data Integration Techniques",
    "SQL Data Management Solutions", "SQL Performance Optimization Tools", "SQL Data Privacy and Security",
    "SQL Cloud Data Security Solutions", "SQL Database Management Techniques", "SQL Data Security Policies",
    "SQL Performance Metrics Analysis Tools", "SQL Data Transformation Tools and Techniques",
    "SQL System Performance Monitoring Tools", "SQL Cloud Database Security", "SQL Data Processing Tools",
    "SQL Data Management Policies", "SQL Database Security Techniques", "SQL Performance Optimization Strategies",
    "SQL Data Privacy Best Practices", "SQL Cloud Database Management Strategies", "SQL System Performance Analysis",
    "SQL Data Integration Solutions", "SQL Performance Monitoring Techniques", "SQL Data Security and Privacy Solutions",
    "SQL Cloud Database Optimization Tools", "SQL Data Management Best Practices", "SQL Performance Tuning Best Practices",
    "SQL Data Privacy Strategies", "SQL Cloud Data Management Tools", "SQL System Performance Metrics",
    "SQL Data Transformation Strategies", "SQL Database Performance Optimization", "SQL Data Security Policies and Procedures",
    "SQL Performance Monitoring Solutions", "SQL Cloud Database Performance Tools", "SQL Data Management Techniques",
    "SQL Data Privacy and Security Strategies", "SQL Performance Metrics Monitoring Tools", "SQL Cloud Database Services",
    "SQL Data Transformation Best Practices", "SQL System Performance Optimization Tools", "SQL Data Security and Privacy Techniques",
    "SQL Cloud Database Management Solutions", "SQL Data Processing Tools and Techniques", "SQL"
];

module.exports = keywords;